export const Question = [
  {
    prompt: 'What is my fav fast food?',
    optionA: 'Pizza',
    optionB: 'Burger',
    optionC: 'Shawarma',
    optionD: 'Platter',
    asnwer: 'B',
  },
  {
    prompt: 'What is my fav place?',
    optionA: 'Mountains',
    optionB: 'Beach',
    optionC: 'Desserts',
    optionD: 'Bed',
    asnwer: 'A',
  },
  {
    prompt: 'What is my fav hobby?',
    optionA: 'Reading',
    optionB: 'Collecting',
    optionC: 'Eating',
    optionD: 'Sleeping',
    asnwer: 'C',
  },
  {
    prompt: 'What is my date of birth?',
    optionA: '18 december',
    optionB: '20 december',
    optionC: '19 december',
    optionD: '21 december',
    asnwer: 'C',
  },
  {
    prompt: 'What I like most?',
    optionA: 'Tea',
    optionB: 'Coffee',
    optionC: 'Shake',
    optionD: 'Juice',
    asnwer: 'A',
  },
  {
    prompt: 'In which college I studied?',
    optionA: 'Punjab',
    optionB: 'Aspire',
    optionC: 'Kips',
    optionD: 'DPS',
    asnwer: 'D',
  },
  {
    prompt: 'What am I afraid of?',
    optionA: 'Grass hopper',
    optionB: 'Lizard',
    optionC: 'Height',
    optionD: 'aunts',
    asnwer: 'A',
  },
  {
    prompt: 'Whom will I date?',
    optionA: 'Sana Javed',
    optionB: 'Disha Patani',
    optionC: 'Deepika padukone',
    optionD: 'Alia But',
    asnwer: 'B',
  },
  {
    prompt: 'My first love?',
    optionA: 'My girlfriend',
    optionB: 'Pakistan',
    optionC: 'My Crush',
    optionD: 'You',
    asnwer: 'B',
  },
  {
    prompt: 'Most frequent word I use?',
    optionA: 'BSDK',
    optionB: 'BC',
    optionC: 'Yes Karwao',
    optionD: 'Wao Fantastic',
    asnwer: 'C',
  },
];
